sources:
- kind: google_doc_html
  config:
    #doc_ids:
    ## Added from command line args
    #- xxxxx
    #- yyyy
transformations:
- kind: nest_bullets
- kind: tag_matching
  config:
    tags:
      add:
        highlighted: '1'
    match_element:
      required_style_sets:
      - backgorund-color: '#ff0000'
      rejected_styles:
        font-weight: bold
- kind: merge_by_tag
  config: 
    acceptable_tag_sets: 
    - ['a']
    - ['b', 'highlight']
    rejeding_tags: ['xx']
- kind: strip_elements
  config:
    remove_style_rules_re: ['.*']
outputs:
- kind: stdout
